logger:
  file:
    path: /var/log/open5gs/nssf.log
  level: info

nssf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7783
    client:
      scp:
        - uri: http://127.0.0.1:7778
      nsi:
        - uri: http://127.0.0.1:7777
          s_nssai:
            sst: 1
