logger:
  file:
    path: /var/log/open5gs/smf.log
  level: debug

smf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7781
    client:
      scp:
        - uri: http://127.0.0.1:7778
  pfcp:
    server:
      # Bind to specific CP container IP â€” avoids loopback IPC interference on 127.0.0.1:8805
      - address: 10.200.100.16
    client:
      upf:
        - address: 10.200.100.17
  gtpc:
    server:
      - address: 0.0.0.0
  gtpu:
    server:
      - address: 0.0.0.0
  metrics:
    server:
      - address: 0.0.0.0
        port: 9091
  session:
    - subnet: 10.206.0.0/16
      gateway: 10.206.0.1
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
  info:
    - s_nssai:
        - sst: 3
          sd: 198153
          dnn:
            - internet
