logger:
  file:
    path: /var/log/open5gs/smf.log
  level: info

smf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7781
    client:
      scp:
        - uri: http://127.0.0.1:7778
  pfcp:
    server:
      - address: 0.0.0.0
    client:
      upf:
        - address: open5gs-upf
  gtpc:
    server:
      - address: 0.0.0.0
  metrics:
    server:
      - address: 0.0.0.0
        port: 9091
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
      dnn: internet
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400
  info:
    - s_nssai:
        - sst: 1
      dnn:
        - internet
